#!/bin/sh
#
# Copyright (c) 2013-2015, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# CONTROL GPIO NUM
export BT_REG_ON=1019
export DEV_WAKE_GPIO=75
export HOST_WAKE_GPIO=59

HELP="Usage $0 {start | stop | restart}"
DUMP_TO_KMSG=/dev/kmsg

do_turn_on_bt () {

	count=`ps -ef | grep bsa_server | grep -v "grep" | wc -l`
	if [ $count == 1 ]; then
		exit 0
	fi

	vdd3v3=`cat /sys/kernel/debug/regulator/rome_vreg/enable`
	if [ $vdd3v3 == "0" ]; then
		echo 1 > /sys/kernel/debug/regulator/rome_vreg/enable
		sleep 0.1
	fi

	#BT_REG_ON control gpio
	if [ ! -d /sys/class/gpio/gpio$BT_REG_ON ]; then
		echo $BT_REG_ON > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio$BT_REG_ON/direction
	fi

	echo 0 >/sys/class/gpio/gpio$BT_REG_ON/value
	sleep 3
	echo 1 >/sys/class/gpio/gpio$BT_REG_ON/value
 
	#BT device wake module host gpio
	if [ ! -d /sys/class/gpio/gpio$DEV_WAKE_GPIO ]; then
		echo 75 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio$DEV_WAKE_GPIO/direction
		echo 0 > /sys/class/gpio/gpio$DEV_WAKE_GPIO/value
	fi

	if [ ! -f /sys/class/bluetooth/wake_gpios/dev_wake ]; then
		echo "####/sys/class/bluetooth/wake_gpios/dev_wake not found!####" > $DUMP_TO_KMSG
		exit 1
	else
		echo $DEV_WAKE_GPIO >/sys/class/bluetooth/wake_gpios/dev_wake
	fi

	#Module host wake bt device gpio
	if [ ! -d /sys/class/gpio/gpio$HOST_WAKE_GPIO ]; then
		echo $HOST_WAKE_GPIO > /sys/class/gpio/export
	fi

	if [ ! -f /sys/class/bluetooth/wake_gpios/host_wake ]; then
		echo "####/sys/class/bluetooth/wake_gpios/host_wake not found!####" > $DUMP_TO_KMSG
		exit 1
	else
		echo $HOST_WAKE_GPIO >/sys/class/bluetooth/wake_gpios/host_wake
	fi

	bsa_server -d /dev/ttyHS0 -p /etc/firmware/cm256/BCM434545.hcd -lpm -b /tmp/btsnoop.cfa > /tmp/bsa.log &
	sleep 3
	bsa_client &
}

do_turn_off_bt () {

	if [ -d /sys/class/gpio/gpio$BT_REG_ON ]; then
		echo 0 > /sys/class/gpio/gpio$BT_REG_ON/value
	fi

	# wlan is power on
	if [ ! -d /sys/devices/7824900.sdhci/mmc_host/mmc0/mmc0:0001 ]; then
		vdd3v3=`cat /sys/kernel/debug/regulator/rome_vreg/enable`
		if [ $vdd3v3 == "1" ]; then
			echo 0 > /sys/kernel/debug/regulator/rome_vreg/enable
			sleep 0.1
		fi
	fi

}

do_ctrl_cld_ll () {
    case "$1" in
    start)
        echo "Starting Bluetooth... $@" > $DUMP_TO_KMSG
		do_turn_on_bt	
 	;;

    stop)
        echo "Stopping Bluetooth..." > $DUMP_TO_KMSG		
		do_turn_off_bt
        ;;

    restart)
        do_ctrl_cld_ll stop
        shift
        do_ctrl_cld_ll start $@

        return $?
        ;;

    *)
        return 1
        ;;
    esac

    return 0
}

do_ctrl_cld_ll $@
if [ $? -ne 0 ]; then
    echo $HELP >&2
    exit 1
fi

